Fix unicycle counting as car
BeamMP/BeamMP-Server pull request #288
Opened 2024-02-12 00:31 UTC by sla-ppy

Fixes #246.

2024-02-12 00:44 UTC, sla-ppy commented
This is a super dirty fix to the issue.
We essentially duct tape a problem which should definitely be revisited later on!

The reason for this dirty fix is because mVehichleData contains both unicycle and vehicle data, and I am unsure if we want it to stay like that.

I propose that in the new protocol we treat unicycle and vehicle data differently because there are questions to be answered like:
- Do we want to allow players to spawn multiple unicycles (as controllable props) or do we want to have a single one representing and acting as the player itself?
- Does it truly make sense to treat unicycles and vechicles differently? 

Benefit of the proposal:
- Counting the unicycle and vehicle counts separately could be toyed around with further.
- Future wise the unicycle could have multiple models for players to have fun with.

2024-02-12 03:05 UTC, sla-ppy commented
Please review my code: @lionkor.

2024-02-12 21:31 UTC, lionkor requested changes
Thanks, logic looks sound and we obv saw it work.

2024-02-12 21:31 UTC, lionkor commented on src/Client.cpp
> +// PROPOSAL: separate unicycles completely from vehicles???
please remove these comments lines 123 and 124

2024-02-12 21:31 UTC, lionkor commented on src/Client.cpp
> +    for (auto& v : mVehicleData) {
Please put a short(ish) comment here explaining the *reasoning* for this solution: For example, it should outline what this fixes, and why this is the fix that was chosen ("it works lol").
You can then remove the comment on L129.

2024-02-14 13:00 UTC, Starystars67 commented
Could I further this topic by suggesting that instead a configuration option be added to specify vehicle names that can be added so they bypass the vehicle limit.

This would be for things like the unicycle as default but can then be expanded to items like cones, bollards, concrete barriers or even pucks.

2024-02-15 09:09 UTC, lionkor commented
> Could I further this topic by suggesting that instead a configuration option be added to specify vehicle names that can be added so they bypass the vehicle limit.
> 
> This would be for things like the unicycle as default but can then be expanded to items like cones, bollards, concrete barriers or even pucks.

I would ask you to make a new feature issue for that, because I'd also like to specify that properly before building it, and I wouldn't want to tack it onto this bug as I want this in the next release.

2024-02-15 09:13 UTC, lionkor commented
@sla-ppy btw in `documentate unicycle dirty fix` the correct form is `document` ;)

2024-02-15 09:13 UTC, lionkor approved these changes
looks good

2024-02-15 09:13 UTC, merged

2024-02-15 10:32 UTC, sla-ppy commented
> @sla-ppy btw in `documentate unicycle dirty fix` the correct form is `document` ;)

![catty](https://github.com/BeamMP/BeamMP-Server/assets/55049912/1a00d44a-7277-4756-8f03-14dcfd5487cb)