Add an entry in serverconfig.toml for the time between update reminders
BeamMP/BeamMP-Server pull request #329
Opened 2024-05-25 18:39 UTC by SaltySnail

fix #321

2024-05-25 18:44 UTC, lionkor requested changes

2024-05-25 18:44 UTC, lionkor commented on include/ChronoWrapper.h
> +    std::chrono::high_resolution_clock::duration TimeFromStringWithLiteral(const std::string time_str);
```suggestion
    std::chrono::high_resolution_clock::duration TimeFromStringWithLiteral(const std::string& time_str);
```

2024-05-25 18:44 UTC, lionkor commented on include/Common.h
> +    static inline Version mVersion { 4, 5, 0 };
```suggestion
    static inline Version mVersion { 3, 5, 0 };
```

2024-05-25 18:44 UTC, lionkor commented on src/ChronoWrapper.cpp
> +    // }
delete

2024-05-25 19:55 UTC, SaltySnail commented on src/ChronoWrapper.cpp
> +    // }
Removed the comments, mentioned in the requested change above, in: [e35bf4f](https://github.com/BeamMP/BeamMP-Server/pull/329/commits/e35bf4fe1520897b18820f11252ad6d557c859e8). Sorry for not giving +1 street cred

2024-06-08 18:09 UTC, lionkor requested changes

2024-06-08 18:09 UTC, lionkor commented on include/Common.h
> +        std::string UpdateReminderTime { "3h" };
Not sure if 3h is good, the default *should* be much quicker, like once every 30 mins(?)

2024-06-08 18:19 UTC, lionkor commented
Also the maximum frequency is not possible, like 1s isn't possible, since it doesnt check for updates *that* much. But that is not a bug because this setting will only be used to turn the frequency *down*

2024-06-08 18:20 UTC, lionkor commented on include/Common.h
> +        std::string UpdateReminderTime { "3h" };
Sorry, meant 30 seconds*

2024-06-08 18:26 UTC, SaltySnail commented on include/Common.h
> +        std::string UpdateReminderTime { "3h" };
fixed in [
f3060f5](https://github.com/BeamMP/BeamMP-Server/pull/329/commits/f3060f5247b13325be5df87a18665bfc21ca7093).

2024-06-10 20:58 UTC, lionkor approved these changes
lgtm

2024-06-10 20:59 UTC, merged