Add allow guests config setting.
BeamMP/BeamMP-Server pull request #335
Opened 2024-06-10 20:11 UTC by SaltySnail

fix #247

2024-06-10 20:57 UTC, lionkor requested changes
Looks great, good solution there with the low prio deny of the auth, very nice. A few small things to fix ;)

2024-06-10 20:57 UTC, lionkor commented on src/TConfig.cpp
> +static constexpr std::string_view EnvStrAllowGuests = "BEAMMP_NO_GUESTS";
`BEAMMP_ALLOW_GUESTS` please to make it easy to guess the ENV

2024-06-10 20:57 UTC, lionkor commented on src/TNetwork.cpp
> +    beammp_debugf("\t NotAllowedWithReason: {} \t AllowGuests: {} \t IsGuest: {}", NotAllowedWithReason, Application::Settings.AllowGuests, Client->IsGuest());
is this debug print necessary? we could/should remove it or make it a `beammp_tracef` so it only shows up in debug builds with debug mode on

2024-06-10 20:57 UTC, lionkor commented on src/TNetwork.cpp
> +        Reason = "No guests are allowed on this server! To join, sign up at; forum.beammp.com.";
```suggestion
        Reason = "No guests are allowed on this server! To join, sign up at: forum.beammp.com.";
```

2024-06-10 21:36 UTC, SaltySnail commented on src/TConfig.cpp
> +static constexpr std::string_view EnvStrAllowGuests = "BEAMMP_NO_GUESTS";
fixed with [6e590ff](https://github.com/BeamMP/BeamMP-Server/pull/335/commits/6e590ff18ad3ea0b09649cdd4652f83003fe70d0)

2024-06-10 21:36 UTC, SaltySnail commented on src/TNetwork.cpp
> +    beammp_debugf("\t NotAllowedWithReason: {} \t AllowGuests: {} \t IsGuest: {}", NotAllowedWithReason, Application::Settings.AllowGuests, Client->IsGuest());
fixed with [e94cfd6](https://github.com/BeamMP/BeamMP-Server/pull/335/commits/e94cfd641d658688335d4789ee42195d440253d3)

2024-06-11 07:01 UTC, lionkor approved these changes
lgtm

2024-06-11 07:01 UTC, merged