Fix disconnect doesn't call onVehicleDeleted
BeamMP/BeamMP-Server pull request #336
Opened 2024-06-13 17:18 UTC by SaltySnail

OnDisconnect sent a packet to the client, which was already disconnected.

2024-06-13 20:04 UTC, lionkor commented
How sure are you that this is the only place where we delete a vehicle? I recall there being more places where we *technically* delete a vehicle but dont do it properly, but im not sure. I'll take a look when i get time regardless

2024-06-13 20:05 UTC, lionkor commented
\+ thank you for taking on this task <3

2024-06-15 18:07 UTC, lionkor requested changes

2024-06-15 18:07 UTC, lionkor commented on src/TServer.cpp
> +                //LuaAPI::MP::Engine->ReportErrors(LuaAPI::MP::Engine->TriggerEvent("onVehicleDeleted", "", c.GetID(), CarID)); //uncomment if this packet is sent to everyone instead of to the client
remove pls

2024-06-15 18:08 UTC, lionkor commented on src/TServer.cpp
> +                //LuaAPI::MP::Engine->ReportErrors(LuaAPI::MP::Engine->TriggerEvent("onVehicleDeleted", "", c.GetID(), CarID)); //uncomment if this packet is sent to everyone instead of to the client
or... should it be there?

2024-06-16 22:15 UTC, SaltySnail commented on src/TServer.cpp
> +                //LuaAPI::MP::Engine->ReportErrors(LuaAPI::MP::Engine->TriggerEvent("onVehicleDeleted", "", c.GetID(), CarID)); //uncomment if this packet is sent to everyone instead of to the client
It needed to be there

2024-06-20 06:55 UTC, lionkor reviewed
Looks good, will need to test it which can take some time. Thank you!

2024-09-18 16:08 UTC, merged