Add stack trace to server lua engine
BeamMP/BeamMP-Server pull request #350
Opened 2024-07-14 01:20 UTC by SaltySnail

2024-07-16 14:03 UTC, lionkor requested changes
lgtm just one little thing

2024-07-16 14:03 UTC, lionkor commented on src/TLuaEngine.cpp
> +static sol::protected_function addTraceback(sol::state_view StateView, sol::protected_function RawFn);
```suggestion
static sol::protected_function AddTraceback(sol::state_view StateView, sol::protected_function RawFn);
```
Let's keep with the absolutely \*\*\*\*\*\*\*\* naming scheme pls

2024-07-20 12:23 UTC, lionkor commented
@SaltySnail you'll have to change it in other places too ;)

2024-07-20 13:06 UTC, SaltySnail reviewed
Fixed not following naming convention in other places. Sorry for the atomic commits, was on my phone

2024-07-20 13:06 UTC, SaltySnail commented on src/TLuaEngine.cpp
> +        Fn = addTraceback(mStateView, Fn);
```suggestion
        Fn = AddTraceback(mStateView, Fn);
```

2024-07-20 13:06 UTC, SaltySnail commented on src/TLuaEngine.cpp
> +static sol::protected_function addTraceback(sol::state_view StateView, sol::protected_function RawFn) {
```suggestion
static sol::protected_function AddTraceback(sol::state_view StateView, sol::protected_function RawFn) {
```

2024-07-20 13:06 UTC, SaltySnail commented on src/TLuaEngine.cpp
> +                    auto Fn = addTraceback(StateView, RawFn);
```suggestion
                    auto Fn = AddTraceback(StateView, RawFn);
```

2024-07-27 17:45 UTC, lionkor commented
WTF lmao

2024-07-27 17:57 UTC, lionkor approved these changes

2024-07-27 17:57 UTC, merged