Add Lua function to get a player's role
BeamMP/BeamMP-Server pull request #366
Opened 2024-09-19 17:53 UTC by WiserTixx

Adds `MP.GetPlayerRole(player_id)` to the Lua API to get a player's role ("USER", "EA", "MDEV", "STAFF", "ET") by their player id.
Currently you can only get someone's role in onPlayerAuth from the parameters and in onVehicleSpawned and onVehicleEdited from the packet data, but not in onPlayerJoin for example without storing it.

2024-09-20 10:39 UTC, lionkor requested changes

2024-09-20 10:39 UTC, lionkor commented on src/TLuaEngine.cpp
> +        return "";
Please use braces

2024-09-20 10:39 UTC, lionkor commented on src/TLuaEngine.cpp
> +        return "";
and remove the expiry check, it's been done in the past but doesn't actually do anything :)

2024-09-20 12:52 UTC, WiserTixx commented
Requested changes have been made.

2024-09-28 18:35 UTC, lionkor commented on src/TLuaEngine.cpp
> +        return "";
Could we please return `nil` instead?

2024-10-05 14:09 UTC, merged